export enum ActionTypes {
  //USER
  ADD_USER_SUCCESS = 'ADD_USER_SUCCESS',
  USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS',
  USER_LOGIN_FAIL = 'USER_LOGIN_FAIL',
  PROCESS_LOGOUT = 'PROCESS_LOGOUT'
}
