export enum ActionTypes {
  //app
  APP_START_UP_COMPLETE = 'APP_START_UP_COMPLETE',

  //USER
  ADD_USER_SUCCESS = 'ADD_USER_SUCCESS',
  USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS',
  USER_LOGIN_FAIL = 'USER_LOGIN_FAIL',
  PROCESS_LOGOUT = 'PROCESS_LOGOUT'
}
